# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2748c9aebfaf0110599886047c18b3d5625ee4a1a6f3dd11ebeb429112c805e1d54b8f07dbf8dea5418f2a8d363e55db6ddb4bc5be821b6d081eb0fd5382036
  app_id: 250930485318799
  secret: 13f6b0b278ce7134dfee8365822e878d
  page_id: 1349876618367737

test:
  secret_key_base: 651942a7d3baa9dc48de1a2166f7ce88d2b8662086c4a0ba4c7715cbad06e57e9bd7057710df34b21c60377297b010ed18e87f0ffc39f7ac546b70f5547d84ae
  app_id: 250930485318799
  secret: 13f6b0b278ce7134dfee8365822e878d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  secret: <%= ENV["FACEBOOK_SECRET"] %>
